name: binsfinderWorkflow
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  REGISTRY: docker.io
  IMAGE_NAME: '${{ github.repository }}'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: login in Docker hub
        uses: docker/login-action@v2
        with:
          image: monatousi/binsfinder
          username: '${{ secrets.DOCKER_USERNAME }}'
          password: '${{ secrets.DOCKER_PASSWORD }}'
      - name: 'Extract metadata (tags, labels) for Docker'
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: '${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}'
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: '{{defaultContext}}'
          push: true
          tags: '${{ steps.meta.outputs.tags }}'
          labels: '${{ steps.meta.outputs.labels }}'
